- .tekton/buildah-remote.yaml
- Dockerfile
Add buildah-remote.yaml to the .tekton directory.  It is referenced later.
> Add buildah-remote.yaml

- .tekton/aap-rag-content-pull-request.yaml
- .tekton/aap-rag-content-push.yaml
Update Konflux build files for sending output to quay.io/ansible/aap-rag-content
> Konflux build setup from default files

- Containerfile-aap
- additional_docs/README.md
- additional_docs/additional_content.txt
- additional_docs/components_versions.txt
- scripts/generate_changelog.sh
- scripts/generate_embeddings-aap.py
- scripts/get_aap_plaintext_docs.sh
See https://issues.redhat.com/browse/AAP-37815
- Automate population of Ansible components' changelog ingestion data `(components_versions.txt)`, in order to avoid manual maintenance
- Reduce max chunk length to increase the amount of documents generated and the relationships between them, and provide better similarity search scores results on sentences. Chatbot focuses more on "details". See [this comment](https://github.com/ansible/aap-rag-content/pull/32#discussion_r1890271228) for more details.
- Need also this update https://github.com/ansible/ansible-chatbot-service/pull/41/files#diff-02ff6b14cc2516cb244b2071f1d406c61a400481fc4d9c7f1c7a2d2b4e7e47eaR120
- Fixes https://github.com/ansible/ansible-lightspeed-va-feedback/issues/3
Depends on: …
> AAP-37815: Fixing wrong Ansible components' versions answers

- .tekton/buildah-remote.yaml
Copy buildah-remote.yaml from openshift-rag-content repo
> Copy buildah-remote.yaml from openshift-rag-content repo

- .tekton/aap-rag-embeddings-image-pull-request.yaml
- .tekton/aap-rag-embeddings-image-push.yaml
Run embeddings Konflux build only when target_branch is embeddings
> Run embeddings Konflux build only when target_branch is embeddings

- .tekton/aap-rag-embeddings-image-pull-request.yaml
- .tekton/aap-rag-embeddings-image-push.yaml
- Containerfile-aap
- Containerfile-embeddings
> Update embeddings image

- scripts/decrypt-mimir.sh
- scripts/mimir-parser.py
Add scripts that are required for Mimir support to the repository.
> Add Mimir scripts

- scripts/mimir-parser.py
For [AAP-39942](https://issues.redhat.com/browse/AAP-39942)
> Add AAP 2.5 doc process to mimir-parser

- scripts/mimir-parser.py
For [AAP-39942](https://issues.redhat.com/browse/AAP-39942)
> Mimir script fix

- additional_docs/.metadata/aap-2_5-authentication-transcription.json
- additional_docs/aap-2_5-authentication-transcription.txt
Add a YouTube video to the `additional_docs` folder.
> Ingest a YouTube video

- pdm.lock.cpu
- pdm.lock.gpu
Update PDM lock files so that dependencies match to the pyproject.toml file.
> Update PDM lock files

- .gitignore
- .tekton/aap-rag-embeddings-image-pull-request.yaml
- .tekton/aap-rag-embeddings-image-push.yaml
https://issues.redhat.com/browse/AAP-42097
> AAP-42097: Add shell and unicode sast pipeline tasks

- scripts/mimir-parser.py
Add debug outputs to mimir-parser.py
> Add debug outputs to mimir-parser.py

- rpms.lock.yaml
> Add rpm.lock.yaml

- rpms.in.yaml
- rpms.lock.yaml
Add libcusparselt0, which is used by torch
> Add libcusparselt0

- Containerfile-aap
> Update gpu-base image

- scripts/generate_embeddings-aap.py
Do not use torch in generate_embeddings-aap.py
> Do not use torch in generate_embeddings-aap.py

- rpms.in.yaml
- rpms.lock.yaml
- scripts/generate_embeddings-aap.py
Update rpm.lock.yaml for libcudnn9-cuda-12
> Update rpm.lock.yaml for libcudnn9-cuda-12

- scripts/generate_embeddings-aap.py
Fix generate_embeddings-aap.py
> Fix generate_embeddings-aap.py

- pyproject.toml
- requirements.txt
- uv.lock
Update pyproject.toml for torch/torchvision following [the instructions on UV docs](https://docs.astral.sh/uv/guides/integration/pytorch/).
> Update pyproject.toml for torch/torchvision

- run.yaml
- scripts/generate_embeddings-llama-stack.py
Use preloaded embeddings model (all-mpnet-base-v2)
This is for [AAP-45774](https://issues.redhat.com/browse/AAP-45774) and is a foundation for [AAP-47230](https://issues.redhat.com/browse/AAP-47230).
> Use preloaded embeddings model (all-mpnet-base-v2)

- requirements.txt
Add index url to torch/torchvision in requirements.txt for Konflux build.
> Add index url to torch/torchvision in requirements.txt
